version: '3.7'
services:
  go:
    container_name: nomad_go
    tty: true
    build:
      dockerfile: ops/docker/go/Dockerfile
      context: .
    command: ./ops/docker/go/command.sh
    volumes:
      - ./:/app
  # python:
  #   container_name: nomad_python
  #   tty: true
  #   build:
  #     dockerfile: ops/docker/python/Dockerfile
  #     context: .
  #   command: ./ops/docker/python/command.sh
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - go