# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/api.proto\x12\x03\x61pi\"\x12\n\x10InferenceRequest\"\"\n\x11InferenceResponse\x12\r\n\x05value\x18\x01 \x01(\x05\x32P\n\x10InferenceService\x12<\n\tInfernece\x12\x15.api.InferenceRequest\x1a\x16.api.InferenceResponse0\x01\x42\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_INFERENCEREQUEST']._serialized_start=24
  _globals['_INFERENCEREQUEST']._serialized_end=42
  _globals['_INFERENCERESPONSE']._serialized_start=44
  _globals['_INFERENCERESPONSE']._serialized_end=78
  _globals['_INFERENCESERVICE']._serialized_start=80
  _globals['_INFERENCESERVICE']._serialized_end=160
# @@protoc_insertion_point(module_scope)
